POST http://localhost:8080/task
Content-Type: application/json


{
    "activated": false,
    "description": "Task de testes usando routes.HTTP"
}

###

GET http://localhost:8080/tasks

###

PUT http://localhost:8080/task/:id
Content-Type: application/json

{
    "activated": false,
    "description": "Segunda Task modifiacada, Uhuuul"
}

###

DELETE http://localhost:8080/task/id
